### ISSUE TITLE
Convert site to Python 3

### ISSUE THREAD

**Issue by JoshData** [codefordc/ancfinder#110]
I think our pdf-to-HTML conversion depends on a library that depends on python2. We can split this dependency out and shell a python2 process if we really have to.

**Comment by jamesfe** [comment]
I think this is a great idea - there are currently 4 projects listed as 'blockers' - but I can start running through the site and running 2to3 and pylinting for python3 if this is still relevant.

Here is a link to an analysis of the requirements.txt file with regards to python3 (may be inaccurate if the libraries haven't updated their status) 
https://caniusepython3.com/check/8e2f6698-7854-44f5-bf4e-d64e09553bce

If anybody knows more about this, let me know - I will be at the hack night this coming Tuesday (28 April 2015).

**Comment by JoshData** [comment]
Hey thanks for taking a look at this!

* django-tinymce: I'm not sure on the status of the library. There are probably alternative HTML inputs we could switch to.
* flup: We will actually drop this soon anyway. We'll need to replace fastcgi with uwsgi to move to Django 1.8 I think.
* pdfminer: We may not be using this. I forget.
* recaptcha-client: We're not using this. It's a dependency of a dependency (`django-registration-pv` pulled in via a github submodule). The dependency is one of my own libraries so we can just patch it to drop the recaptcha-client dependency.

**Comment by jamesfe** [comment]
Cool.  I'll set up the dev environment and do a little work on this tomorrow maybe, should be up and running prior to the Tuesday meetup.
