### ISSUE TITLE
Update 'use my current location' to use proj4js + DC reverseGeocode endpoint

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [codefordc/ancfinder#126]
alternatively we could use this http://citizenatlas.dc.gov/usng/getusng.asmx?op=MD_LLtoSPCS to go from lat/lng to Maryland State Plane (instead of the JS-based solution)

**Comment by mkalish** [comment]
Closing this as won't fix for now as we are redirecting new development to a more slimmed down version of the app.
