### ISSUE TITLE
Unexpected End of File

### ISSUE THREAD

**Issue by dfdx2** [codefordc/ancfinder#130]
when trying to recreate the site using the vagrant instructions after typing vagrant up I get the error message below. 

default: stdin: is not a tty
default: /vagrant/provision.sh: line 32: syntax error: unexpected end of file

**Comment by JKesMc9tqIQe9M** [comment]
Hi -- does Vagrant issue any other messages before that? Can you provide the complete sequence of commands you've done and the output that was produced? This might help to figure out the problem. Thanks.

**Comment by dfdx2** [comment]
Hi, this is the complete output after I type vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ancfinder'...

[KProgress: 90%
[K==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: ancfinder_default_1421349937425_65367
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 => 8000 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/dfdx2/PycharmProjects/ancfinder
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: /vagrant/provision.sh: line 32: syntax error: unexpected end of file

**Comment by mkalish** [comment]
We've moved the setup guides over to use docker, which should hopefully provide an easy setup.
