### ISSUE TITLE
Replace ancs.json with data in database

### ISSUE THREAD

**Issue by JoshData** [codefordc/ancfinder#134]
We are loading data from `data/scraped-anc.json` into the new db model.

Currently we load `ancs.json` in models.py into `anc_data` and then pass that into various templates.

Only some of the data in ancs.json is now in the database model. So we need to convert just accesses to *that* data into accesses into the database. Use `CommissionerInfo.get(anc, smd, field_name)`, where field_name is like "first_name" or something.

**Comment by JoshData** [comment]
I'll try to finish the homepage stuff in Javascript.

**Comment by stvnrlly** [comment]
Nice, let me know how I can pitch in.

**Comment by JoshData** [comment]
Okay I think I've actually gotten it working. To test, we need to remove all of the commissioner-specific info from ancs.json so we can be sure everything is coming from the database. Anyone want to give that a go? Would be good to have a script to do it so we can run it on the live ancs.json file when we're ready to deploy this update.

**Comment by JoshData** [comment]
Ba-dum it is done.
