### ISSUE TITLE
Add monthly calendar to Overview tab, pre-populated with highlighted dates of meetings for each ANC and its committees

### ISSUE THREAD

**Issue by emkap01** [codefordc/ancfinder#136]
It would be really useful to have a small monthly calendar somewhere on the "Overview" tab, with the dates of the ANC and related committee meetings each highlighted.  

Right now it's possible for users to dig that information up on their own by going to the "committees" tab and then figuring out what the "first Tuesday of the month" translates into for the current month, but that requires a few extra steps most people may be unwilling to take.

**Comment by mkalish** [comment]
Closing this as won't fix for now as we are redirecting new development to a more slimmed down version of the app.
