### ISSUE TITLE
keep official and submitted information separate

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/ancfinder#138]
Right now, we keep one field for something like a commissioner's email. It might make more sense to keep `official_email` and `submitted_email` separate, so that there's always the supposedly-official option available in case the submitted information is faulty.

**Comment by JoshData** [comment]
This is a part of a broader issue of how to review submissions.

The db is set up like version control so we can always roll back. We could mark submissions as `needs-approval` so they don't go live until approved, or we could mark submissions as `verified` so we have safe points to roll-back to as needed.

**Comment by stvnrlly** [comment]
I don't want to require review for 2 main reasons: (1) I'm not sure how we'd verify things, and (2) it requires time and effort. What's the downside of providing both the official and submitted information?

If we do need to do some sort of verification, a complicated but more hands-off approach could be to implement a reputation system for users.
