### ISSUE TITLE
Update setup docs 

### ISSUE THREAD

**Issue by mkalish** [codefordc/ancfinder#153]
Issue:
Clean up the set up docs so that it is easier to on board new folks

- [x] Docker documentation, the most recent one done and contains all the necessary infrastructure to run the site locally.  Its available [here](https://github.com/codefordc/ancfinder/tree/feature/docker)
- [x] Vagrant documentation; its pretty outdated, so feel free to delete; it overlaps pretty heavily with docker
- [x] Cloud 9; I've never used it, also could probably be deleted
- [x] Update static; I would save this for last as these are probably need the most work

**Comment by rbmy** [comment]
You can assign this to me as I am working on it.

**Comment by mkalish** [comment]
This is done with the merge of V2
