### ISSUE TITLE
Google Maps key expired

### ISSUE THREAD

**Issue by austinbrian** [codefordc/ancfinder#163]
We'll need to either update the key or switch to a new service.

**Comment by msimcha** [comment]
Would it be worth using https://wiki.openstreetmap.org/wiki/Export#Embeddable_HTML as a replacement?

**Comment by rbmy** [comment]
Code for DC actually has a map box account. @mkalish has the key and we can use that as an environment variable for the map.

**Comment by mkalish** [comment]
Replacing with mapbox will be in the v2
